apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-storage-dep
  labels:
    app: spring-cloud-storage-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-storage-ex
  template:
    metadata:
      labels:
        app: spring-cloud-storage-ex
    spec:
      containers:
        - name: spring-cloud-storage-ex
          image: sridocker2023/spring-boot-images:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-storage-svc
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: spring-cloud-storage-ex